### ISSUE TITLE
[FEAT] Rewrite the whole repo in Java

### ISSUE THREAD

**Issue by issy** [rHomelab/LabBot-Cogs#109]
# Overview
## Describe the solution you'd like
Python is slow. You snooze, you lose

## Is this suggestion based on an existing problem? If so, please describe it
The bot is currently written in Python. I want it to not be written in Python

# DoD
* 100% Java domination

# Stretch
* Maybe use Excel as the database

**Comment by tigattack** [comment]
You're fired.

**Comment by UntouchedWagons** [comment]
Why not Lua?

**Comment by issy** [comment]
> Why not Lua?

sounds unholy

**Comment by UntouchedWagons** [comment]
> 
> 
> > Why not Lua?
> 
> sounds unholy

Yes
