### ISSUE TITLE
[FEAT] Enforcer enhancements

### ISSUE THREAD

**Issue by tigattack** [rHomelab/LabBot-Cogs#129]
# Overview
## Describe the solution you'd like
1. Message user with enforced content (just text is fine).
2. Include enforced content in log.
3. Include enforced channel in log.
4. Fix minimum guild age - Had it set to 3600 (seconds) and it nuked a message from an account with a guild age of >1095 _days_. Haven't tested minimumdiscordage, pls check.
5. Bug in `[p]enforcer status` pagination: `Page 1/0`
![image](https://user-images.githubusercontent.com/10629864/110667017-be852480-81c1-11eb-90bc-f509a3e41b02.png)

_Totally discarding our issue template rules here and fucking up issue tracking and management because I'm busy and cba filling out and raising 4 separate issues 👀_

**Comment by kdavis** [comment]
https://github.com/rHomelab/LabBot-Cogs/blob/develop/enforcer/enforcer.py#L207 and https://github.com/rHomelab/LabBot-Cogs/blob/develop/enforcer/enforcer.py#L196 needs to change to use `.total_seconds()`
