### ISSUE TITLE
[BUG] Wrong message messages aren't removed

### ISSUE THREAD

**Issue by tigattack** [rHomelab/LabBot-Cogs#133]
**Describe the bug**
The message the bot posts to alert the user that they've entered the wrong message is not removed upon successful verification of that user.

**To Reproduce**
1. Say `I have reed and agree to the #welcome-rules` (or any other incorrect phrase) in #lobby.
2. See wrong message warning.
3. Verify successfully.
4. See "wrong message" message still there.

**Expected behavior**
If a user enters the wrong message, triggerering the wrong message function, the message that's posted by the bot in response should be cleaned up once that user is verified, whether that be a re-attempt by themselves or manual override by a mod.

**Screenshots**
People have entered the wrong message and then verified, leaving us with this:
![image](https://user-images.githubusercontent.com/10629864/110440736-e6389780-80b0-11eb-8c17-979217e97d80.png)

**Additional context**

**Comment by issy** [comment]
This seems to be because the configured `wrongmsg` attribute doesn't mention the user

**Comment by tigattack** [comment]
Gotcha. Thanks Issy. I'll reflect this in the docs.
