### ISSUE TITLE
[FEAT] Letters cog enhancements

### ISSUE THREAD

**Issue by issy** [rHomelab/LabBot-Cogs#160]
# Overview
## Describe the solution you'd like

These changes are all tied to the letters cog
- if resulting message is too long (> 2000 chars) it should pagify the output or not output anything at all
- option to output without the code block/only the code block
- maybe expand the accepted characters to include punctuation? Have to be careful to only accept certain punctuation here in case of ping escaping

## Is this suggestion based on an existing problem? If so, please describe it

The bot errors out if resulting message is > 2000 chars instead of failing gracefully

# DoD
- Fail gracefully if resulting message is > 2000 chars OR pagify output

# Stretch
- `--raw` and `--without-raw` options in command (flag naming subject to change)
- Accept some punctuation in command (maybe `!?,.'`?)

**Comment by tigattack** [comment]
I'm going to limit the output length since I don't want to deal with pagify rn. This error would suggest bots are limited to 4000 characters, so I'm going to go for that.

```py
raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 4000 or fewer in length.
```

**Comment by issy** [comment]
That's odd, Discord's own docs say it's a 2000 character limit 😂 I can only assume they changed it recently. I agree that limiting the output is the more reasonable choice here

**Comment by WaitroseDev** [comment]
> That's odd, Discord's own docs say it's a 2000 character limit 😂 I can only assume they changed it recently. I agree that limiting the output is the more reasonable choice here

Was upped (At least in embed bodies) about a week after the user upgrade [See this post in discord devs](https://discord.com/channels/613425648685547541/697138785317814292/860278223236890624)
