### ISSUE TITLE
[FEAT] Add GUI timestamps to cogs which use timestamps

### ISSUE THREAD

**Issue by issy** [rHomelab/LabBot-Cogs#163]
# Overview
## Describe the solution you'd like

Discord have introduced a new feature that allows you to show timestamps in a format local to the user. For cogs such as notes, reports, etc it would be useful to move to this format, as it is nicer to read.
[Here is an overview of how it works](https://discord.com/developers/docs/reference#message-formatting-formats)

## Is this suggestion based on an existing problem? If so, please describe it

# DoD
* Timestamps converted to this format in relevant cogs

No stretch goals for this. Triage needed to determine which cogs this is relevant to, and which format would be best suited in each case.

**Comment by tigattack** [comment]
Relevant cogs:

* Enforcer
* Notes
* Quotes?
* Report
