### ISSUE TITLE
[FEAT] Tags cog

### ISSUE THREAD

**Issue by issy** [rHomelab/LabBot-Cogs#177]
# Overview

A cog to store "tags" created by users. These tags can be referenced at a later time using `[p]tag <tag_name>`. The idea is that this would supersede most of the functionality given by the CustomCommands core cog - with the stipulation that tags can also be created by users, and that (unlike custom commands) they don't pollute the global command namespace (eg. `[p]tag foo` instead of `[p]foo`).

# Commands
```
[p]tag <tag_name>
[p]tag search <search_term>
[p]tag create <tag_name> <tag_content>
[p]tag stats <optional[member]>
[p]tag info <tag_name>
[p]tag edit <tag_name> <new_content>
[p]tag delete <tag_name>
[p]tag alias create <alias_name> <tag_name>
[p]tag alias delete <alias_name>
[p]tag claim <tag_name>
[p]tag transfer <tag_name> <member>
```

# DoD
- [x] All members have the ability to create tags
- [x] Anyone can edit a tag *that they own*
- [x] Tags can be deleted by moderators and the member who owns said tag
- [x] Tag aliases can be created by anyone
- [x] If a member leaves the server, their tags can be claimed by anyone
- [x] Tag ownership can be transferred by a moderator or the tag owner

# Stretch
- [x] List of members who can't create tags and respective moderator commands to add/remove members from said list

**Comment by tigattack** [comment]
Love this, awesome idea 👍

**Comment by BeryJu** [comment]
very poggers
