### ISSUE TITLE
[FEAT] Total Users Banned count

### ISSUE THREAD

**Issue by narokuu** [rHomelab/LabBot-Cogs#243]
# Overview
Requesting a command to see the total number of users banned by labbot

# Commands
bantotal
totalyeeted
yeetlist

**Comment by tigattack** [comment]
Cheers naro.

Let's go with `[p]bancount`. We can alias other, more joke-y triggers in our own instance of Red if we wish.

**Comment by tigattack** [comment]
As a note for whoever implements this (I may do so myself, so more of a note-to-self...), this will be incredibly easy with a simple call to `len(await ctx.guild.bans())`.
