### ISSUE TITLE
[FEAT] Fuzzy matching for self-verification.

### ISSUE THREAD

**Issue by tigattack** [rHomelab/LabBot-Cogs#33]
# Overview
Users are currently unable to self-verify if they do not type the verification string _exactly_. Fuzzy matching would bring a better user experience with no detriment to moderation or security.

# DoD
* User must be able to verify with phrases similar to but not exactly `I have read and agree to the #welcome-rules`

**Comment by issy** [comment]
I toooootally didn't accidentally click the close button 😂
