### ISSUE TITLE
[FEAT] Edit warnings and notes

### ISSUE THREAD

**Issue by tigattack** [rHomelab/LabBot-Cogs#66]
# Overview
## Describe the solution you'd like
Edit option for warnings and notes.

## Is this suggestion based on an existing problem? If so, please describe it

# DoD
* `^warnings edit` and/or `^notes edit` command.

**Comment by kdavis** [comment]
Edit just the contents of the warning/note or should there be further possible field changes?

**Comment by tigattack** [comment]
I guess just the note content is all we need, timestamp and user shouldn't really be necessary.

Having said that, conversion between note & warning would be very useful, as often notes are used instead of warnings.
