### ISSUE TITLE
[FEAT] Implementation of GateKeeper

### ISSUE THREAD

**Issue by themiddlegeek** [rHomelab/LabBot-Cogs#74]
# Overview

# DoD
* `gt block` and `gt unblock`
* error message when verification is attempted on blocked user, `Verification Failed. Please contact a moderator for more information`

# Stretch
* Ping mods that are online or make a note in modchat when verification is attempted on a blocked user. `Verification failed. Mods have been notified and will reach out to you when available.`

**Comment by tigattack** [comment]
Suggest this be part of existing verify cog.

**Comment by issy** [comment]
Closing because this functionality has been implemented in the verify cog
