### ISSUE TITLE
[FEAT] W E B S C A L E

### ISSUE THREAD

**Issue by themiddlegeek** [rHomelab/LabBot-Cogs#75]
# Overview
Detection of someone typing `w e b s c a l e` and bot message in letter emojis.

# DoD
* Bot must watch for `w e b s c a l e` and reply when seen.

# Stretch
* Fuzzy detection of w e b s c a l e with any case of character.

**Comment by tigattack** [comment]
This would be good as part of a general auto-reply cog.
