### ISSUE TITLE
[FEAT] lastfm Cog Improvements

### ISSUE THREAD

**Issue by MonsterMuffin** [rHomelab/LabBot-Cogs#77]
# Overview
## Describe the solution you'd like

Remove playcount from Last.fm as it chats gas. 

Add 'Now Playing:' to fm now before the embed. 

## Is this suggestion based on an existing problem? If so, please describe it

# DoD
* An idea that must be completed for this task to be merged.

# Stretch
* Proposed ideas that aren't required but could be added with more discussion.

**Comment by tigattack** [comment]
Not our cog. PR has been created to fix the play count issue: https://github.com/kennnyshiwa/kennnyshiwa-cogs/pull/34
